from wsgi import app

#THIS CODE CREATE BY @RAJ_SARKAR
#THIS CODE CREATE BY @RAJ_SARKAR
#THIS CODE CREATE BY @RAJ_SARKAR
#THIS CODE CREATE BY @RAJ_SARKAR
#THIS CODE CREATE BY @RAJ_SARKAR
#THIS CODE CREATE BY @RAJ_SARKAR
